---
# Download Oracle Java
#
# Installing Java while fetching the distribution from Oracle is
# a nightmare.
#
# Version information is a huge mess with Oracle Java. Naming of
# files, directories and zip archives is never consistent and one
# never knows what they are up to next.
#
# What this does is trying to use Ansible capabilities while
# allowing a usable installation of the Oracle Java JDK.


# Install a persistent local data path for ansible to manage
#   downloading Java.
- name: Install local ansible data path directory
  tags: java
  local_action: file
    state=directory
    dest={{ local_ansible_data_path }}


# Downloaded archives are verified with shasum command
- name: Install Java redis packages sha256sum files
  tags: java
  with_items:
    - java.sha256sum
    - java_jce.sha256sum
  local_action: template
    src={{ item }}.j2
    dest={{ local_ansible_data_path }}/{{ item }}
    mode=0644


# Test whether we need to download Java (again).
- name: Verify Java redis package sha256sum
  tags: java
  ignore_errors: true
  failed_when: false
  register: java_oracle_redis_exists
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java.sha256sum

- name: Verify Java JCE redis package sha256sum
  tags: java
  ignore_errors: true
  failed_when: false
  register: java_oracle_redis_jce_exists
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java_jce.sha256sum


# Ensure there is no broken download on the local disk
- name: Remove possible broken Java redis package
  tags: java
  when: java_oracle_redis_exists.rc != 0
  local_action: file
    state=absent
    dest={{ local_ansible_data_path }}/{{ java_oracle_redis_filename }}

- name: Remove possible broken Java JCE redis package
  tags: java
  when: java_oracle_redis_jce_exists.rc != 0
  local_action: file
    state=absent
    dest={{ local_ansible_data_path }}/{{ java_oracle_redis_jce_filename }}


# Download the Java distribution from Oracle to the workstations'
# filesystem. Yeah, right, accept license agreement...
# This allows to distribute Java to any number of hosts in the
# context of a local network instead of downloading Java again
# for every role/node which depends on this role.
- name: Download Oracle Java redis package
  tags: java
  register: java_oracle_redis_download
  when: java_oracle_redis_exists.rc != 0
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ java_oracle_redis_mirror }}
    chdir={{ local_ansible_data_path }}
    creates={{ local_ansible_data_path }}/{{ java_oracle_redis_filename }}

- name: Download Oracle Java JCE redis package
  tags: java
  register: java_oracle_redis_jce_download
  when: java_oracle_redis_jce_exists.rc != 0
  local_action: command
    curl
      --location
      --insecure
      --remote-name
      --cookie oraclelicense={{ java_oracle_curl_cookie }}
      --cookie-jar /tmp/{{ java_oracle_redis_filename }}.cookie
      {{ java_oracle_mirror_jce }}/{{ java_oracle_redis_jce_filename }}
    chdir={{ local_ansible_data_path }}
    creates={{ local_ansible_data_path }}/{{ java_oracle_redis_jce_filename }}

# Fixup possible users umask issues
- name: Ensure downloaded archives are world readable
  tags: java
  with_items: ["{{ java_oracle_redis_filename }}", "{{ java_oracle_redis_jce_filename }}"]
  local_action: file
    dest={{ local_ansible_data_path }}/{{ item }}
    mode=0644

# Test whether downloaded redistributable package passes sha256sum
- name: Verify Oracle Java redis package sha256sum
  tags: java
  when: java_oracle_redis_download|changed
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java.sha256sum

- name: Verify Java JCE redis package sha256sum
  tags: java
  when: java_oracle_redis_jce_download|changed
  local_action: command
    shasum
      --algorithm 256
      --portable
      --check
      --status
      {{ local_ansible_data_path }}/java_jce.sha256sum
